name: ci
on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train (quick smoke)
        run: python -m ml.train
      - name: Run tests
        run: python -m pytest -q
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/
      - name: Read metrics
        id: metrics
        run: |
          echo "model_kind=$(jq -r .model_kind artifacts/metrics.json)" >> $GITHUB_OUTPUT
          echo "model_version=$(jq -r .model_version artifacts/metrics.json)" >> $GITHUB_OUTPUT
          echo "rmse=$(jq -r .rmse artifacts/metrics.json)" >> $GITHUB_OUTPUT