name: release
on:
  push:
    tags:
      - 'v*'


permissions:
  contents: write
  packages: write


jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model (produce artifacts/)
        run: python -m ml.train
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Read metrics
        id: metrics
        run: |
          { echo 'body<<EOF'; cat artifacts/metrics.json; echo EOF; } >> "$GITHUB_OUTPUT"

      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE .

      - name: Smoke test container
        run: |
          docker run -d -p 8000:8000 --name api ${{ env.IMAGE }}
          sleep 3
          curl -sSf http://localhost:8000/health | jq .
          docker logs api
          docker rm -f api

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ env.IMAGE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}
            **Metrics:**
            ```
            ${{ steps.metrics.outputs.metrics_body }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}